    # "includedPrimaryTypes": ["afghani_restaurant", "african_restaurant", "american_restaurant", "asian_restaurant",
    #     "barbecue_restaurant", "brazilian_restaurant", "buffet_restaurant", "chinese_restaurant", "french_restaurant",
    #     "greek_restaurant", "hamburger_restaurant", "indian_restaurant", "indonesian_restaurant", "italian_restaurant",
    #     "japanese_restaurant", "korean_restaurant", "lebanese_restaurant", "mediterranean_restaurant", "mexican_restaurant",
    #     "middle_eastern_restaurant", "pizza_restaurant", "ramen_restaurant", "restaurant", "seafood_restaurant",
    #     "spanish_restaurant", "steak_house", "sushi_restaurant", "thai_restaurant", 
    #     "turkish_restaurant", "vegetarian_restaurant", "vietnamese_restaurant"],
    # "excludedPrimaryTypes": ["acai_shop", "bagel_shop", "bakery", "bar", "bar_and_grill", "breakfast_restaurant",
    #     "brunch_restaurant", "cafe", "cafeteria", "candy_store", "cat_cafe", "chocolate_factory", "chocolate_shop", "coffee_shop",
    #     "confectionery", "deli", "dessert_restaurant", "dessert_shop", "dog_cafe", "donut_shop", "fast_food_restaurant",
    #     "fine_dining_restaurant", "food_court", "ice_cream_shop", "juice_shop", "meal_delivery", "meal_takeaway", "pub",
    #     "sandwich_shop", "tea_house", "vegan_restaurant", "wine_bar"],
    # "excludedTypes": ["acai_shop", "bagel_shop", "bakery", "bar", "candy_store", "cat_cafe", "chocolate_factory", 
    #     "chocolate_shop", "coffee_shop", "dessert_restaurant", "dessert_shop", "dog_cafe", "donut_shop",
    #     "fast_food_restaurant", "food_court", "ice_cream_shop", "juice_shop", "pub",
    #     "sandwich_shop", "tea_house","wine_bar"],



INCLUDED_PRIMARY_TYPES = [
    "restaurant",
    "meal_delivery",
    "meal_takeaway",
]

EXCLUDED_PRIMARY_TYPES = [
    "bar",
    "store",
    "grocery_or_supermarket",
    "bakery",
    "cafe",
    "drugstore",
    "pharmacy",
    "liquor_store",
    "convenience_store",
    "department_store",
    "gas_station",
    "home_goods_store",
    "laundry",
    "library",
    "marina",
    "movie_theater",
    "museum",
    "park",
    "parking",
    "pet_store",
    "physiotherapist",
    "place_of_worship",
    "playground",
    "police",
    "post_office",
    "primary_school",
    "secondary_school",
    "shoe_store",
    "shopping_mall",
    "spa",
    "stadium",
    "storage",
    "subway_station",
    "supermarket",
    "swimming_pool",
    "tourist_attraction",
    "train_station",
    "transit_station",
    "travel_agency",
    "university",
    "veterinary_care",
    "zoo",
    "accounting",
    "administrative_area_level_1",
    "administrative_area_level_2",
    "administrative_area_level_3",
    "administrative_area_level_4",
    "administrative_area_level_5",
    "airport",
    "amusement_park",
    "aquarium",
    "art_gallery",
    "atm",
    "bank",
    "beauty_salon",
    "bicycle_store",
    "book_store",
    "bowling_alley",
    "bus_station",
    "campground",
    "car_dealer",
    "car_rental",
    "car_repair",
    "car_wash",
    "cemetery",
    "church",
    "city_hall",
    "clothing_store",
    "courthouse",
    "dentist",
    "doctor",
    "electrician",
    "electronics_store",
    "embassy",
    "fire_station",
    "florist",
    "funeral_home",
    "furniture_store",
    "gym",
    "hair_care",
    "hardware_store",
    "hindu_temple",
    "hospital",
    "insurance_agency",
    "jewelry_store",
    "lawyer",
    "light_rail_station",
    "local_government_office",
    "locksmith",
    "lodging",
    "mosque",
    "movie_rental",
    "moving_company",
    "night_club",
    "painter",
    "plumber",
    "real_estate_agency",
    "roofing_contractor",
    "rv_park",
    "school",
    "synagogue",
    "taxi_stand",
    "taxi_stand",
    "train_station",
    "travel_agency",
    "university",
]

EXCLUDED_TYPES = [
    "bar",
    "bar & grill",
    "sports bar",
    "wine bar",
    "beer garden",
    "pub",
    "irish pub",
    "gastropub",
    "brewpub",
    "cocktail bar",
    "dive bar",
    "hotel bar",
    "karaoke bar",
    "lounge",
    "juice bar",
    "coffee shop",
    "cafe",
    "bakery",
    "pastry shop",
    "dessert shop",
    "ice cream shop",
    "frozen yogurt shop",
    "bubble tea",
    "tea house",
    "boba shop",
    "donut shop",
    "cupcake shop",
    "candy store",
    "chocolate shop",
    "popcorn store",
    "pretzel store",
    "bagel shop",
    "smoothie shop",
    "health food store",
    "organic food store",
    "natural food store",
    "vitamin & supplements store",
    "herbal medicine store",
    "grocery store",
    "supermarket",
    "convenience store",
    "liquor store",
    "wine store",
    "beer store",
    "drugstore",
    "pharmacy",
    "chemist",
    "discount store",
    "dollar store",
    "variety store",
    "general store",
    "department store",
    "warehouse store",
    "wholesale store",
    "outlet store",
    "shopping mall",
    "clothing store",
    "shoe store",
    "jewelry store",
    "accessories store",
    "gift shop",
    "souvenir store",
    "bookstore",
    "newsstand",
    "music store",
    "video game store",
    "toy store",
    "hobby store",
    "craft store",
    "art supply store",
    "fabric store",
    "sewing store",
    "knitting store",
    "yarn store",
    "home goods store",
    "furniture store",
    "electronics store",
    "hardware store",
    "paint store",
    "garden center",
    "nursery",
    "florist",
    "pet store",
    "aquarium store",
    "bird store",
    "reptile store",
    "sporting goods store",
    "bicycle shop",
    "outdoor sports store",
    "hunting store",
    "fishing store",
    "gun store",
    "ski shop",
    "surf shop",
    "skateboard shop",
    "pawn shop",
    "thrift store",
    "consignment shop",
    "antique store",
    "flea market",
    "farmers market",
    "butcher shop",
    "fish market",
    "cheese shop",
    "ethnic grocery store",
    "health food store",
    "gourmet grocery store",
    "specialty food store",
    "tobacco shop",
    "vape shop",
    "cigar shop",
    "adult entertainment store",
    "sex shop",
    "lingerie store",
    "costume store",
    "party store",
    "bridal shop",
    "formal wear store",
    "uniform store",
    "shoe repair shop",
    "watch repair shop",
    "jewelry repair shop",
    "engraving shop",
    "trophy shop",
    "framing store",
    "photo shop",
    "camera store",
    "copy shop",
    "printing shop",
    "shipping store",
    "post office",
    "mailbox service",
    "notary public",
    "passport photo service",
    "currency exchange",
    "check cashing service",
    "pawn shop",
    "lottery retailer",
    "atm",
    "bank",
    "credit union",
    "insurance agency",
    "real estate agency",
    "travel agency",
    "car rental agency",
    "taxi service",
    "limo service",
    "bus station",
    "train station",
    "subway station",
    "airport",
    "ferry terminal",
    "marina",
    "gas station",
    "car wash",
    "car repair shop",
    "tire shop",
    "oil change service",
    "auto parts store",
    "motorcycle shop",
    "rv park",
    "campground",
    "hotel",
    "motel",
    "hostel",
    "bed & breakfast",
    "guesthouse",
    "resort",
    "casino",
    "movie theater",
    "performing arts theater",
    "concert hall",
    "comedy club",
    "nightclub",
    "bar",
    "lounge",
    "pool hall",
    "bowling alley",
    "arcade",
    "amusement park",
    "water park",
    "zoo",
    "aquarium",
    "museum",
    "art gallery",
    "library",
    "park",
    "playground",
    "stadium",
    "arena",
    "gym",
    "fitness center",
    "yoga studio",
    "pilates studio",
    "dance studio",
    "martial arts school",
    "swimming pool",
    "tennis court",
    "golf course",
    "skating rink",
    "ski resort",
    "spa",
    "sauna",
    "massage therapist",
    "beauty salon",
    "hair salon",
    "nail salon",
    "barbershop",
    "tattoo parlor",
    "piercing studio",
    "tanning salon",
    "dry cleaner",
    "laundromat",
    "tailor",
    "dressmaker",
    "seamstress",
    "cobbler",
    "locksmith",
    "electrician",
    "plumber",
    "carpenter",
    "painter",
    "roofer",
    "gardener",
    "landscaper",
    "exterminator",
    "pool cleaner",
    "house cleaner",
    "moving company",
    "storage facility",
    "funeral home",
    "cemetery",
    "church",
    "mosque",
    "synagogue",
    "temple",
    "place of worship",
    "school",
    "university",
    "college",
    "preschool",
    "daycare center",
    "tutoring service",
    "test preparation center",
    "language school",
    "driving school",
    "flight school",
    "hospital",
    "clinic",
    "doctor's office",
    "dentist's office",
    "optometrist's office",
    "chiropractor's office",
    "physical therapist's office",
    "mental health clinic",
    "rehabilitation center",
    "nursing home",
    "assisted living facility",
    "pharmacy",
    "veterinarian",
    "animal hospital",
    "pet shelter",
    "police station",
    "fire station",
    "courthouse",
    "city hall",
    "embassy",
    "military base",
    "community center",
    "senior center",
    "youth center",
    "event venue",
    "wedding venue",
    "conference center",
    "convention center",
    "exhibition center",
    "banquet hall",
    "ballroom",
    "auditorium",
    "planetarium",
    "observatory",
    "winery",
    "brewery",
    "distillery",
    "farm",
    "factory",
    "office building",
    "coworking space",
    "virtual office",
    "business center",
    "bank",
    "financial institution",
    "law firm",
    "accounting firm",
    "consulting firm",
    "marketing agency",
    "advertising agency",
    "public relations firm",
    "media company",
    "publishing company",
    "broadcasting station",
    "telecommunications company",
    "internet service provider",
    "web design company",
    "software company",
    "it consulting firm",
    "data processing service",
    "call center",
    "employment agency",
    "temporary employment agency",
    "staffing agency",
    "human resources consulting firm",
    "translation service",
    "interpretation service",
    "security service",
    "private investigator",
    "bail bonds service",
    "courier service",
    "delivery service",
    "freight forwarding service",
    "logistics service",
    "warehousing service",
    "self-storage facility",
    "truck rental agency",
    "car shipping service",
    "towing service",
    "parking garage",
    "parking lot",
    "airport parking",
    "valet parking service",
    "bicycle rental service",
    "scooter rental service",
    "boat rental service",
    "rv rental agency",
    "party equipment rental service",
    "tool rental service",
    "equipment rental service",
    "construction company",
    "home builder",
    "remodeling service",
    "handyman service",
    "hvac contractor",
    "electrical contractor",
    "plumbing contractor",
    "painting contractor",
    "flooring contractor",
    "roofing contractor",
    "landscaping contractor",
    "paving contractor",
    "concrete contractor",
    "demolition contractor",
    "excavation contractor",
    "septic system service",
    "well drilling service",
    "solar energy equipment supplier",
    "waste management service",
    "recycling center",
    "junk removal service",
    "document shredding service",
    "hazardous waste disposal service",
    "environmental consulting firm",
    "agricultural service",
    "forestry service",
    "mining company",
    "oil and gas company",
    "utility company",
    "water company",
    "electric company",
    "natural gas company",
    "propane supplier",
    "heating oil supplier",
    "coal supplier",
    "wood pellet supplier",
    "solar energy company",
    "wind energy company",
    "geothermal energy company",
    "hydroelectric power plant",
    "nuclear power plant",
    "biomass power plant",
    "waste-to-energy plant",
    "research institute",
    "laboratory",
    "testing laboratory",
    "calibration laboratory",
    "forensic laboratory",
    "medical laboratory",
    "dental laboratory",
    "optical laboratory",
    "non-profit organization",
    "charitable organization",
    "religious organization",
    "political organization",
    "labor union",
    "professional association",
    "trade association",
    "business association",
    "fraternal organization",
    "social club",
    "country club",
    "yacht club",
    "gun club",
    "historical society",
    "arts organization",
    "cultural center",
    "ethnic organization",
    "environmental organization",
    "animal welfare organization",
    "human rights organization",
    "civil rights organization",
    "political party",
    "advocacy group",
    "lobbying firm",
    "public opinion research firm",
    "polling station",
    "government office",
    "federal government office",
    "state government office",
    "local government office",
    "county government office",
    "city government office",
    "town government office",
    "village government office",
    "tribal government office",
    "embassy",
    "consulate",
    "military base",
    "coast guard station",
    "national guard armory",
    "port authority",
    "airport authority",
    "transit authority",
    "housing authority",
    "redevelopment agency",
    "planning department",
    "building department",
    "health department",
    "education department",
    "parks and recreation department",
    "public works department",
    "transportation department",
    "water department",
    "sanitation department",
    "environmental protection agency",
    "consumer protection agency",
    "emergency management agency",
    "law enforcement agency",
    "fire department",
    "correctional facility",
    "courthouse",
    "post office",
    "library",
    "museum",
    "art gallery",
    "performing arts center",
    "sports facility",
    "park",
    "playground",
    "zoo",
    "aquarium",
    "botanical garden",
    "arboretum",
    "nature preserve",
    "wildlife refuge",
    "national park",
    "state park",
    "county park",
    "city park",
    "historic site",
    "monument",
    "landmark",
    "tourist attraction",
    "visitor center",
    "convention center",
    "exhibition center",
    "fairground",
    "amusement park",
    "water park",
    "theme park",
    "casino",
    "racetrack",
    "stadium",
    "arena",
    "theater",
    "cinema",
    "concert hall",
    "opera house",
    "amphitheater",
    "nightclub",
    "bar",
    "lounge",
    "restaurant",
    "cafe",
    "coffee shop",
    "bakery",
    "deli",
    "pizzeria",
    "fast food restaurant",
    "food truck",
    "catering service",
    "banquet hall",
    "wedding venue",
    "event planning service",
    "party supply store",
    "florist",
    "photographer",
    "videographer",
    "dj service",
    "musician",
    "band",
    "entertainer",
    "magician",
    "clown",
    "impersonator",
    "balloon artist",
    "face painter",
    "caricaturist",
    "fortune teller",
    "psychic",
    "astrologer",
    "tarot card reader",
    "palm reader",
    "medium",
    "channeler",
    "spiritual advisor",
    "life coach",
    "motivational speaker",
    "personal trainer",
    "nutritionist",
    "dietitian",
    "massage therapist",
    "acupuncturist",
    "chiropractor",
    "physical therapist",
    "occupational therapist",
    "speech therapist",
    "audiologist",
    "optometrist",
    "ophthalmologist",
    "dentist",
    "orthodontist",
    "periodontist",
    "endodontist",
    "oral surgeon",
    "cosmetic dentist",
    "pediatric dentist",
    "doctor",
    "physician",
    "surgeon",
    "cardiologist",
    "dermatologist",
    "endocrinologist",
    "gastroenterologist",
    "hematologist",
    "immunologist",
    "nephrologist",
    "neurologist",
    "oncologist",
    "obstetrician-gynecologist",
    "ophthalmologist",
    "orthopedic surgeon",
    "otolaryngologist",
    "pathologist",
    "pediatrician",
    "plastic surgeon",
    "podiatrist",
    "psychiatrist",
    "pulmonologist",
    "radiologist",
    "rheumatologist",
    "urologist",
    "allergist",
    "anesthesiologist",
    "emergency medicine physician",
    "family medicine physician",
    "geriatrician",
    "hospitalist",
    "infectious disease physician",
    "intensivist",
    "medical geneticist",
    "nuclear medicine physician",
    "pain management physician",
    "palliative care physician",
    "preventive medicine physician",
    "sports medicine physician",
    "travel medicine physician",
    "urgent care physician",
    "hospital",
    "clinic",
    "medical center",
    "urgent care center",
    "emergency room",
    "intensive care unit",
    "operating room",
    "recovery room",
    "maternity ward",
    "pediatric ward",
    "psychiatric ward",
    "rehabilitation center",
    "nursing home",
    "assisted living facility",
    "hospice",
    "pharmacy",
    "drugstore",
    "medical laboratory",
    "blood bank",
    "diagnostic imaging center",
    "dialysis center",
    "fertility clinic",
    "sleep disorder clinic",
    "mental health clinic",
    "addiction treatment center",
    "counseling service",
    "psychotherapy service",
    "social worker",
    "case manager",
    "home health care service",
    "personal care assistant",
    "companion care service",
    "respite care service",
    "adult day care center",
    "child care service",
    "preschool",
    "kindergarten",
    "elementary school",
    "middle school",
    "high school",
    "vocational school",
    "technical school",
    "trade school",
    "community college",
    "college",
    "university",
    "graduate school",
    "professional school",
    "business school",
    "law school",
    "medical school",
    "dental school",
    "pharmacy school",
    "nursing school",
    "engineering school",
    "art school",
    "music school",
    "dance school",
    "drama school",
    "culinary school",
    "cosmetology school",
    "barber school",
    "massage therapy school",
    "flight school",
    "driving school",
    "tutoring service",
    "test preparation service",
    "language school",
    "adult education school",
    "continuing education program",
    "distance education program",
    "online school",
    "homeschool",
    "library",
    "archive",
    "museum",
    "art gallery",
    "historical society",
    "science museum",
    "children's museum",
    "natural history museum",
    "planetarium",
    "observatory",
    "zoo",
    "aquarium",
    "botanical garden",
    "arboretum",
    "nature center",
    "wildlife park",
    "safari park",
    "animal sanctuary",
    "petting zoo",
    "farm",
    "ranch",
    "vineyard",
    "winery",
    "brewery",
    "distillery",
    "cidery",
    "meadery",
    "sake brewery",
    "shochu distillery",
    "awamori distillery",
    "factory",
    "manufacturing plant",
    "industrial park",
    "warehouse",
    "distribution center",
    "fulfillment center",
    "power plant",
    "water treatment plant",
    "sewage treatment plant",
    "recycling plant",
    "landfill",
    "quarry",
    "mine",
    "oil rig",
    "gasworks",
    "construction site",
    "demolition site",
    "roadwork site",
    "bridge",
    "tunnel",
    "dam",
    "canal",
    "pipeline",
    "power line",
    "communication tower",
    "satellite dish",
    "antenna",
    "lighthouse",
    "water tower",
    "wind turbine",
    "solar panel array",
    "geothermal power plant",
    "hydroelectric power plant",
    "nuclear power plant",
    "biomass power plant",
    "waste-to-energy plant",
    "cemetery",
    "graveyard",
    "mausoleum",
    "columbarium",
    "crematorium",
    "funeral home",
    "mortuary",
    "church",
    "chapel",
    "cathedral",
    "basilica",
    "temple",
    "shrine",
    "mosque",
    "masjid",
    "synagogue",
    "gurdwara",
    "mandir",
    "vihara",
    "monastery",
    "convent",
    "ashram",
    "retreat center",
    "place of worship",
    "religious school",
    "seminary",
    "bible college",
    "yeshiva",
    "madrasa",
    "religious bookstore",
    "religious goods store",
    "wedding chapel",
    "government building",
    "federal building",
    "state capitol",
    "county courthouse",
    "city hall",
    "town hall",
    "village hall",
    "post office",
    "customs house",
    "border crossing",
    "embassy",
    "consulate",
    "military base",
    "fort",
    "armory",
    "arsenal",
    "naval station",
    "air force base",
    "coast guard station",
    "national guard armory",
    "police station",
    "sheriff's office",
    "state police station",
    "highway patrol station",
    "fire station",
    "emergency services building",
    "civil defense center",
    "prison",
    "jail",
    "correctional facility",
    "detention center",
    "juvenile detention center",
    "courthouse",
    "judicial center",
    "law library",
    "public defender's office",
    "district attorney's office",
    "probation office",
    "parole office",
    "social security office",
    "department of motor vehicles",
    "department of revenue",
    "department of taxation",
    "department of labor",
    "department of commerce",
    "department of agriculture",
    "department of education",
    "department of health",
    "department of human services",
    "department of environmental protection",
    "department of transportation",
    "department of housing and urban development",
    "department of veterans affairs",
    "department of homeland security",
    "department of defense",
    "department of justice",
    "department of state",
    "department of the interior",
    "department of energy",
    "department of treasury",
    "central intelligence agency",
    "federal bureau of investigation",
    "national security agency",
    "drug enforcement administration",
    "federal aviation administration",
    "transportation security administration",
    "environmental protection agency",
    "food and drug administration",
    "centers for disease control and prevention",
    "national institutes of health",
    "national science foundation",
    "national aeronautics and space administration",
    "smithsonian institution",
    "library of congress",
    "national archives and records administration",
    "government printing office",
    "united states mint",
    "bureau of engraving and printing",
    "internal revenue service",
    "social security administration",
    "united states postal service",
    "amtrak",
    "passenger rail service",
    "freight rail service",
    "public transportation",
    "bus service",
    "subway service",
    "light rail service",
    "tram service",
    "ferry service",
    "taxi service",
    "ride-sharing service",
    "limousine service",
    "airport shuttle service",
    "bicycle sharing service",
    "scooter sharing service",
    "car sharing service",
    "trucking company",
    "shipping company",
    "moving company",
    "courier company",
    "logistics company",
    "warehousing company",
    "freight forwarding company",
    "customs brokerage",
    "port",
    "harbor",
    "marina",
    "airport",
    "heliport",
    "spaceport",
    "railway station",
    "bus station",
    "subway station",
    "light rail station",
    "tram stop",
    "ferry terminal",
    "taxi stand",
    "truck stop",
    "rest area",
    "welcome center",
    "tourist information center",
    "highway",
    "street",
    "road",
    "avenue",
    "boulevard",
    "lane",
    "drive",
    "court",
    "place",
    "square",
    "circle",
    "plaza",
    "promenade",
    "esplanade",
    "boardwalk",
    "pedestrian mall",
    "alley",
    "footpath",
    "trail",
    "bikeway",
    "bridge",
    "tunnel",
    "overpass",
    "underpass",
    "roundabout",
    "intersection",
    "crosswalk",
    "sidewalk",
    "curb",
    "median",
    "guardrail",
    "sound barrier",
    "toll booth",
    "parking meter",
    "traffic signal",
    "street light",
    "sign",
    "billboard",
    "bench",
    "bus shelter",
    "phone booth",
    "mailbox",
    "fire hydrant",
    "manhole",
    "utility pole",
    "power line",
    "communication tower",
    "satellite dish",
    "antenna",
    "water tower",
    "wind turbine",
    "solar panel",
    "park",
    "playground",
    "garden",
    "forest",
    "field",
    "meadow",
    "hill",
    "mountain",
    "valley",
    "canyon",
    "cave",
    "beach",
    "dune",
    "island",
    "peninsula",
    "cape",
    "bay",
    "gulf",
    "strait",
    "channel",
    "sound",
    "fjord",
    "cove",
    "lagoon",
    "estuary",
    "delta",
    "river",
    "stream",
    "creek",
    "brook",
    "canal",
    "lake",
    "pond",
    "reservoir",
    "swamp",
    "marsh",
    "bog",
    "fen",
    "wetland",
    "ocean",
    "sea",
    "ice cap",
    "glacier",
    "iceberg",
    "geyser",
    "hot spring",
    "volcano",
    "earthquake zone",
    "fault line",
    "desert",
    "oasis",
    "tundra",
    "savanna",
    "prairie",
    "steppe",
    "taiga",
    "rainforest",
    "jungle",
    "mangrove",
    "coral reef",
    "kelp forest",
    "seamount",
    "abyssal plain",
    "continental shelf",
    "continental slope",
    "ocean trench",
    "hydrothermal vent",
    "cold seep",
    "brine pool",
    "asphalt volcano",
    "mud volcano",
    "pingo",
    "permafrost",
    "thermokarst",
    "patterned ground",
    "rock glacier",
    "moraine",
    "esker",
    "drumlin",
    "kame",
    "outwash plain",
    "erratic",
    "cirque",
    "arête",
    "horn",
    "hanging valley",
    "u-shaped valley",
    "fjord",
    "ria",
    "sound",
    "tarn",
    "paternoster lake",
    "kettle lake",
    "misfit stream",
    "braided river",
    "meander",
    "oxbow lake",
    "floodplain",
    "levee",
    "delta",
    "alluvial fan",
    "bajada",
    "pediment",
    "inselberg",
    "butte",
    "mesa",
    "plateau",
    "canyon",
    "gorge",
    "ravine",
    "gulch",
    "coulee",
    "badlands",
    "hoodoo",
    "natural arch",
    "natural bridge",
    "cave",
    "cavern",
    "sinkhole",
    "karst tower",
    "cenote",
    "lava tube",
    "volcanic crater",
    "caldera",
    "lava dome",
    "cinder cone",
    "shield volcano",
    "stratovolcano",
    "geyser field",
    "fumarole field",
    "solfatara field",
    "mudpot",
    "hot spring terrace",
    "travertine terrace",
    "tufa tower",
    "sand dune",
    "erg",
    "yardang",
    "ventifact",
    "desert pavement",
    "playa",
    "salt flat",
    "sabkha",
    "oasis",
    "wadi",
    "arroyo",
    "dry wash",
    "ephemeral stream",
    "intermittent stream",
    "perennial stream",
    "spring",
    "seep",
    "waterfall",
    "cascade",
    "rapids",
    "whirlpool",
    "eddy",
    "current",
    "tide",
    "wave",
    "breaker",
    "surf",
    "swell",
    "tsunami",
    "storm surge",
    "seiche",
    "ice floe",
    "ice field",
    "ice shelf",
    "ice cap",
    "glacier",
    "iceberg",
    "polynya",
    "lead",
    "pressure ridge",
    "ice cave",
    "moulin",
    "crevasse",
    "serac",
    "ogive",
    "firn",
    "névé",
    "snowfield",
    "avalanche chute",
    "cornice",
    "sastrugi",
    "rime ice",
    "glaze ice",
    "hoarfrost",
    "dew",
    "fog",
    "mist",
    "haze",
    "smog",
    "vog",
    "cloud",
    "rain",
    "drizzle",
    "snow",
    "sleet",
    "hail",
    "graupel",
    "ice pellets",
    "freezing rain",
    "virga",
    "sunshower",
    "rainbow",
    "halo",
    "corona",
    "aureole",
    "glory",
    "brocken spectre",
    "crepuscular rays",
    "anticrepuscular rays",
    "sun pillar",
    "moon pillar",
    "light pillar",
    "parhelic circle",
    "subsun",
    "parhelion",
    "anthelion",
    "paraselene",
    "subselene",
    "circumzenithal arc",
    "circumhorizontal arc",
    "supralateral arc",
    "infralateral arc",
    "parry arc",
    "lowitz arc",
    "tangent arc",
    "aurora",
    "airglow",
    "zodiacal light",
    "gegenschein",
    "green flash",
    "blue flash",
    "red flash",
    "mirage",
    "fata morgana",
    "shimmer",
    "heat haze",
    "scintillation",
    "twinkling",
    "refraction",
    "reflection",
    "diffraction",
    "interference",
    "scattering",
    "absorption",
    "emission",
    "polarization",
    "doppler effect",
    "redshift",
    "blueshift",
    "gravitational lensing",
    "aberration of light",
    "atmospheric seeing",
    "extinction",
    "albedo",
    "color temperature",
    "brightness",
    "luminosity",
    "magnitude",
    "declination",
    "right ascension",
    "azimuth",
    "altitude",
    "zenith",
    "nadir",
    "meridian",
    "ecliptic",
    "celestial equator",
    "celestial pole",
    "celestial sphere",
    "constellation",
    "asterism",
    "star",
    "planet",
    "dwarf planet",
    "moon",
    "asteroid",
    "comet",
    "meteoroid",
    "meteor",
    "meteorite",
    "galaxy",
    "nebula",
    "star cluster",
    "supernova",
    "black hole",
    "quasar",
    "pulsar",
    "neutron star",
    "white dwarf",
    "red giant",
    "blue giant",
    "yellow dwarf",
    "brown dwarf",
    "black dwarf",
    "protostar",
    "protoplanetary disk",
    "exoplanet",
    "interstellar medium",
    "intergalactic medium",
    "cosmic microwave background",
    "dark matter",
    "dark energy",
    "universe",
    "multiverse",
    "big bang",
    "inflation",
    "string theory",
    "m-theory",
    "quantum mechanics",
    "general relativity",
    "special relativity",
    "classical mechanics",
    "thermodynamics",
    "electromagnetism",
    "optics",
    "acoustics",
    "fluid dynamics",
    "plasma physics",
    "condensed matter physics",
    "atomic physics",
    "nuclear physics",
    "particle physics",
    "astrophysics",
    "cosmology",
    "biophysics",
    "geophysics",
    "atmospheric physics",
    "oceanography",
    "climatology",
    "meteorology",
    "geology",
    "paleontology",
    "archaeology",
    "anthropology",
    "sociology",
    "psychology",
    "economics",
    "political science",
    "history",
    "linguistics",
    "philosophy",
    "theology",
    "mathematics",
    "statistics",
    "computer science",
    "information science",
    "library science",
    "engineering",
    "medicine",
    "dentistry",
    "pharmacy",
    "nursing",
    "veterinary medicine",
    "agriculture",
    "forestry",
    "fisheries",
    "mining",
    "manufacturing",
    "construction",
    "transportation",
    "communication",
    "energy",
    "water",
    "waste management",
    "environmental protection",
    "public health",
    "education",
    "research",
    "defense",
    "law enforcement",
    "emergency services",
    "government",
    "politics",
    "business",
    "finance",
    "insurance",
    "real estate",
    "tourism",
    "hospitality",
    "entertainment",
    "sports",
    "recreation",
    "arts",
    "culture",
    "media",
    "publishing",
    "broadcasting",
    "telecommunications",
    "internet",
    "software",
    "hardware",
    "electronics",
    "robotics",
    "biotechnology",
    "nanotechnology",
    "materials science",
    "aerospace",
    "automotive",
    "maritime",
    "rail",
    "logistics",
    "retail",
    "wholesale",
    "e-commerce",
    "marketing",
    "advertising",
    "public relations",
    "consulting",
    "legal services",
    "accounting services",
    "human resources",
    "translation services",
    "interpretation services",
    "security services",
    "cleaning services",
    "catering services",
    "event planning services",
    "photography services",
    "videography services",
    "graphic design services",
    "web design services",
    "interior design services",
    "architecture services",
    "landscape architecture services",
    "urban planning services",
    "surveying services",
    "appraisal services",
    "inspection services",
    "testing services",
    "certification services",
    "accreditation services",
    "licensing services",
    "permitting services",
    "notary services",
    "courier services",
    "delivery services",
    "postal services",
    "freight services",
    "warehousing services",
    "storage services",
    "moving services",
    "towing services",
    "parking services",
    "rental services",
    "leasing services",
    "repair services",
    "maintenance services",
    "installation services",
    "demolition services",
    "excavation services",
    "drilling services",
    "blasting services",
    "welding services",
    "machining services",
    "fabrication services",
    "printing services",
    "binding services",
    "engraving services",
    "embroidery services",
    "laundry services",
    "dry cleaning services",
    "tailoring services",
    "shoe repair services",
    "watch repair services",
    "jewelry repair services",
    "locksmith services",
    "gunsmithing services",
    "taxidermy services",
    "funeral services",
    "cremation services",
    "cemetery services",
    "pet services",
    "dog walking services",
    "pet sitting services",
    "pet grooming services",
    "pet boarding services",
    "veterinary services",
    "animal training services",
    "pest control services",
    "extermination services",
    "fumigation services",
    "termite control services",
    "mosquito control services",
    "rodent control services",
    "wildlife removal services",
    "tree services",
    "lawn care services",
    "landscaping services",
    "gardening services",
    "irrigation services",
    "pool cleaning services",
    "snow removal services",
    "chimney sweep services",
    "gutter cleaning services",
    "window cleaning services",
    "carpet cleaning services",
    "upholstery cleaning services",
    "house cleaning services",
    "office cleaning services",
    "janitorial services",
    "security guard services",
    "private investigation services",
    "bodyguard services",
    "alarm system services",
    "fire protection services",
    "emergency medical services",
    "ambulance services",
    "hospital services",
    "clinic services",
    "doctor services",
    "dentist services",
    "optometrist services",
    "chiropractor services",
    "physical therapy services",
    "mental health services",
    "counseling services",
    "social work services",
    "home health care services",
    "nursing home services",
    "assisted living services",
    "hospice services",
    "pharmacy services",
    "laboratory services",
    "diagnostic imaging services",
    "dialysis services",
    "rehabilitation services",
    "addiction treatment services",
    "weight loss services",
    "fitness services",
    "personal training services",
    "yoga instruction services",
    "pilates instruction services",
    "martial arts instruction services",
    "dance instruction services",
    "music instruction services",
    "art instruction services",
    "tutoring services",
    "test preparation services",
    "language instruction services",
    "driving instruction services",
    "flight instruction services",
    "child care services",
    "preschool services",
    "elementary school services",
    "secondary school services",
    "higher education services",
    "vocational training services",
    "adult education services",
    "continuing education services",
    "online education services",
    "library services",
    "museum services",
    "art gallery services",
    "performing arts services",
    "sports and recreation services",
    "park services",
    "zoo services",
    "aquarium services",
    "botanical garden services",
    "historical society services",
    "cultural center services",
    "community center services",
    "senior center services",
    "youth center services",
    "religious services",
    "charitable services",
    "non-profit services",
    "political organization services",
    "labor union services",
    "professional association services",
    "trade association services",
    "business association services",
    "fraternal organization services",
    "social club services",
    "country club services",
    "yacht club services",
    "gun club services",
    "environmental organization services",
    "animal welfare organization services",
    "human rights organization services",
    "civil rights organization services",
    "advocacy group services",
    "lobbying services",
    "public opinion research services",
    "polling services",
    "government services",
    "federal government services",
    "state government services",
    "local government services",
    "county government services",
    "city government services",
    "town government services",
    "village government services",
    "tribal government services",
    "embassy services",
    "consulate services",
    "military services",
    "coast guard services",
    "national guard services",
    "port authority services",
    "airport authority services",
    "transit authority services",
    "housing authority services",
    "redevelopment agency services",
    "planning department services",
    "building department services",
    "health department services",
    "education department services",
    "parks and recreation department services",
    "public works department services",
    "transportation department services",
    "water department services",
    "sanitation department services",
    "environmental protection agency services",
    "consumer protection agency services",
    "emergency management agency services",
    "law enforcement services",
    "fire department services",
    "correctional facility services",
    "courthouse services",
    "post office services",
]

BIGQUERY_DATASET_ID = "restaurants_dataset"
BIGQUERY_TABLE_ID = "restaurants_table"

# Secret Manager Secret IDs
MAPS_API_KEY_SECRET_ID = "maps-key"
RESTAURANT_BUCKET_NAME_SECRET_ID = "restaurant_bucket_name"
COORDINATES_TOP_LEFT_SUFFIX = "_top_left"
COORDINATES_BOTTOM_RIGHT_SUFFIX = "_bottom_right"
