steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/restaurants/restaurant-finder-image:latest'
      - 'run_restaurant_finder/'
    env:
      - PROJECT_ID=$PROJECT_ID
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-docker.pkg.dev/$PROJECT_ID/restaurants/restaurant-finder-image:latest'
    env:
      - PROJECT_ID=$PROJECT_ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - deploy
      - restaurant-finder-job
      - --image=europe-docker.pkg.dev/$PROJECT_ID/restaurants/restaurant-finder-image:latest
      - --region=europe-west1
      - --cpu=2
      - --memory=2Gi
      - --max-retries=0
      - --set-env-vars=PROJECT_ID=$PROJECT_ID